src/TestBank.Web/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestBank.Common.Models;
using TestBank.Service;
using Microsoft.AspNetCore.Identity;
using TestBank.Web.Extensions;
using System.Linq;
using AutoMapper;
using TestBank.Common.ViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TestBank.Web.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ITransactionService _transactionService;
        private readonly AccountDbContext _context;
        private readonly IMapper _mapper;

        public TransactionController(IAccountService accountService, ITransactionService transactionService, AccountDbContext context, IMapper mapper)
        {
            _accountService = accountService;
            _transactionService = transactionService;
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            string userId = HttpContext.User.GetUserId();
            var transactions = _transactionService.GetTransactions(_context, userId).OrderByDescending(x=>x.CreatedAt).ToList();
            return View(_mapper.Map<List<TransactionViewModel>>(transactions));
        }

        [HttpGet]
        public IActionResult DepositAmount()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DepositAmount(DepositAmountViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var transactionToAdd = _mapper.Map<Transaction>(model);
            transactionToAdd.AccountId = HttpContext.User.GetUserId();

            _transactionService.AddTransaction(_context, transactionToAdd);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult TransferAmount()
        {
            ViewBag.Users = GetAccounts(HttpContext.User.GetUserId());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult TransferAmount(TransferAmountViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Users = GetAccounts(HttpContext.User.GetUserId());
                return View(model);
            }

            if (model.Amount > _transactionService.GetCurrentBalanace(_context, HttpContext.User.GetUserId()))
            {
                ModelState.AddModelError("Amount", "Amount should not be greater than balance");
                return View(model);
            }

            var transectionToDebit = new Transaction
            {
                Amount = model.Amount * -1,
                AccountId = HttpContext.User.GetUserId()
            };
            _transactionService.AddTransaction(_context, transectionToDebit);

            var transactionToCredit = _mapper.Map<Transaction>(model);
            _transactionService.AddTransaction(_context, transactionToCredit);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult WithdrawAmount()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WithdrawAmount(WithdrawAmountViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.Amount > _transactionService.GetCurrentBalanace(_context, HttpContext.User.GetUserId()))
            {
                ModelState.AddModelError("Amount", "Amount should not be greater than balance");
                return View(model);
            }

            var transactionToAdd = _mapper.Map<Transaction>(model);
            transactionToAdd.AccountId = HttpContext.User.GetUserId();

            _transactionService.AddTransaction(_context, transactionToAdd);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult GetBalance()
        {
            return Json(_transactionService.GetCurrentBalanace(_context, HttpContext.User.GetUserId()));  
        }


        #region Helpers

        private List<SelectListItem> GetAccounts(string currentUserId)
        {
            List<SelectListItem> userAccounts = new List<SelectListItem>();

            var accounts = _accountService.GetAccounts(_context)
                                          .Where(x => x.Id != currentUserId)
                                          .ToList();

            foreach (var account in accounts)
            {
                userAccounts.Add(new SelectListItem { Text = account.UserName, Value = account.Id });
            }

            return userAccounts;
        }

        #endregion

    }
}

src/TestBank.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestBank </title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TestBank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TestBank </p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>